import { Metadata } from "next"

import Navbar from "../components/navbar/Navbar"

import {Monda} from "next/font/google"
import "./global.css"
import dynamic from "next/dynamic"


export const metadata: Metadata = {
  title: 'Johan - Next.js',
  description: 'Generated by Next.js',
}

const fontMonda = Monda({
  weight: ["400","700"],
  style: ["normal"],
  subsets: ["latin","latin-ext","vietnamese"]
})



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontMonda.className}>
      <body className="bg-zinc-100 w-full h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  )
}
